apiVersion: v1
kind: Secret
metadata:
  name: url-shortener-secrets
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgrespassword
  DATABASE_URL: postgres://postgres:postgrespassword@postgres-db:5432/urlshortener
  REDIS_URL: redis://redis-cache:6379
